In [1]:
a=10,20,30
type(a)

tuple

In [2]:
import numpy as np

a=np.array(a)
type(a)

numpy.ndarray

In [3]:
b=np.array([[1,2,3],[4,5,6]])
type (b)
np.ndim(b)

2

In [4]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c
# np.ndim(c)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
c.size

12

In [6]:
c.shape

(2, 2, 3)

In [7]:
d=np.arange(1,101,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
# Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)
d1 = np.arange(22,71,2)
d1

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [9]:
# Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)
d2 = np.arange(21,72,2)
d2

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [10]:
d2 = d2.astype("float")
d2.dtype

dtype('float64')

In [11]:
ar = np.linspace(1,50,5)
ar

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [12]:
c[1][1][0]

np.int64(10)

In [13]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
c[1,0,1:3]

array([8, 9])

In [15]:
mat = np.arange(1,37)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [16]:
mat=mat.reshape(6,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [17]:
# Extract rows 2 to 4 and columns 3 to 5.
mat[1:4,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [18]:
# Extract every 2nd row and every 2nd column.
mat[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [19]:
# Reverse the row order but keep columns same.
mat[::-1]

array([[31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [20]:
mat


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [21]:
mat[2:4,2:4]

array([[15, 16],
       [21, 22]])

In [22]:
#without vectorization
def fun(l):
    return l*5

l = [1,2,3,4,5]
m = list(map(fun,l))
m

[5, 10, 15, 20, 25]

In [23]:
#with vectorization

la = np.array([1,2,3,4,5])
la*5

array([ 5, 10, 15, 20, 25])

In [24]:
# broadcasting
a=[1,2,3]
b=[[1],[2],[3]]
print(a)
print(b)
a+b

[1, 2, 3]
[[1], [2], [3]]


[1, 2, 3, [1], [2], [3]]

In [25]:
a=np.array([1,2,3])
print(a)
b=np.array([[4],[5],[6]])
print(b)
c=a+b

[1 2 3]
[[4]
 [5]
 [6]]


In [26]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [27]:
np.ndim(c)

2

In [28]:
a=np.array([1,2,3])
print(a)
b=np.array([[4],[5],[6]])
print(b)
c=a*b
c

[1 2 3]
[[4]
 [5]
 [6]]


array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [29]:
# Math Function
np.sum(c)

np.int64(90)

In [31]:
np.argmax(c)

np.int64(8)

In [32]:
c

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [33]:
np.argmin(c)

np.int64(0)